/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JInternalFrame;

/**
 *
 * @author alam
 */
public class home_pengelola extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private static home_pengelola instance = null;
    
    public home_pengelola() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    public void DekstopPane(JInternalFrame fm){
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.add(fm);
    }
    
    
    public void addIndukanListener(ActionListener listener){
        indukan.addActionListener(listener);
    }
    public void addKolamListener(ActionListener listener){
        kolam.addActionListener(listener);
    }
    public void addLogoutListener(ActionListener listener){
        logout.addActionListener(listener);
    }
    public void addSuhuListener(ActionListener listener){
        btnSuhu.addActionListener(listener);
    }
    public void addKeasamanListener(ActionListener listener){
        btnKeasaman.addActionListener(listener);
    }
    public void addKondisiListener(ActionListener listener){
        btnKondisi.addActionListener(listener);
    }
    
    public void menuTombol(boolean a){
        this.btnSuhu.setVisible(a);
        this.btnKeasaman.setVisible(a);
        this.btnKondisi.setVisible(a);
    }
    
    public static home_pengelola getInstance(){
        if (instance == null) {
            instance = new home_pengelola();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gambarNavigasi1 = new codingGambar.gambarNavigasi();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        indukan = new javax.swing.JButton();
        kolam = new javax.swing.JButton();
        btnSuhu = new javax.swing.JButton();
        btnKeasaman = new javax.swing.JButton();
        btnKondisi = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        gambarLogin1 = new codingGambar.gambarLogin();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("PENGELOLA");

        logout.setText("Logout");

        indukan.setBackground(new java.awt.Color(255, 51, 51));
        indukan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        indukan.setText("INDUK");

        kolam.setBackground(new java.awt.Color(255, 51, 51));
        kolam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kolam.setText("KOLAM");

        btnSuhu.setBackground(new java.awt.Color(102, 102, 255));
        btnSuhu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSuhu.setText("SUHU");

        btnKeasaman.setBackground(new java.awt.Color(102, 102, 255));
        btnKeasaman.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKeasaman.setText("KEASAMAN");

        btnKondisi.setBackground(new java.awt.Color(102, 102, 255));
        btnKondisi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKondisi.setText("KONDISI");

        javax.swing.GroupLayout gambarNavigasi1Layout = new javax.swing.GroupLayout(gambarNavigasi1);
        gambarNavigasi1.setLayout(gambarNavigasi1Layout);
        gambarNavigasi1Layout.setHorizontalGroup(
            gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarNavigasi1Layout.createSequentialGroup()
                .addGroup(gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gambarNavigasi1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logout)
                            .addComponent(jLabel1)))
                    .addGroup(gambarNavigasi1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(indukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kolam, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                            .addGroup(gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnKondisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKeasaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSuhu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        gambarNavigasi1Layout.setVerticalGroup(
            gambarNavigasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarNavigasi1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout)
                .addGap(63, 63, 63)
                .addComponent(indukan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kolam, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeasaman, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarNavigasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarNavigasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 550));

        javax.swing.GroupLayout gambarLogin1Layout = new javax.swing.GroupLayout(gambarLogin1);
        gambarLogin1.setLayout(gambarLogin1Layout);
        gambarLogin1Layout.setHorizontalGroup(
            gambarLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        gambarLogin1Layout.setVerticalGroup(
            gambarLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(gambarLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_pengelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_pengelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_pengelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_pengelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_pengelola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeasaman;
    private javax.swing.JButton btnKondisi;
    private javax.swing.JButton btnSuhu;
    private codingGambar.gambarLogin gambarLogin1;
    private codingGambar.gambarNavigasi gambarNavigasi1;
    private javax.swing.JButton indukan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kolam;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
